# Generated by Django 6.0.4 on 2026-04-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_repairorderitem_delete_repairmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemethod',
            name='demonstration_video',
            field=models.FileField(blank=True, null=True, upload_to='services/videos/'),
        ),
    ]
