# Generated by Django 6.0.4 on 2026-04-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_servicemethod_demonstration_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
